#!/usr/bin/env node
// make-figma/build.js — builds the standalone Make → Figma set from the repo's Make modules:
//   make-figma/plugin/    the Figma plugin "Make → Figma" (Make only; talks to port 41779; own plugin id)
//   make-figma/extension/ the Chrome extension (talks to port 41779)
//   node make-figma/build.js
// The plugin's build engine (kit runtime + Make converter) is the generated part of plugin/sap-bridge/code.js, so it is refreshed
// first with build/plugin-bundle.js and then cut out here. plugin/sap-bridge (the old SAP Bridge) is only READ, never changed.
'use strict';
const fs = require('fs'), path = require('path'), { execFileSync } = require('child_process');
const ROOT = path.join(__dirname, '..'), OUT = path.join(__dirname, 'plugin'), PORT = 41779;
execFileSync(process.execPath, [path.join(ROOT, 'build', 'plugin-bundle.js')], { stdio: 'ignore' });
const src = fs.readFileSync(path.join(ROOT, 'plugin', 'sap-bridge', 'code.js'), 'utf8');
const cut = (from, to) => { const a = src.indexOf(from), b = src.indexOf(to, a + 1); if (a < 0 || b < 0) throw new Error(`markers not found: ${from} … ${to}`); return src.slice(a, b); };

const engine = cut('// ── GENERATED RUNTIME', '// ─── helpers');            // kit runtime + Make converter + tables
const helpers = cut('// ─── helpers', '// ─── start');                // qs, api, send, later, fileKeyNow, showNode
const logos = cut('async function placeTreeLogos', 'async function runTreeJob') + cut('function namedLike', 'function inGroup');
const make = cut('// ─── Make → SAP: a pasted', '// ─── UI messages')
  .replace('In the project folder run: node build/mailbox.js ensure — or paste a copied design instead.', 'Start it: node make-figma/ctl.js start')
  .replace('In the project folder run: node build/mailbox.js restart', 'Restart it: node make-figma/ctl.js restart');
if (/mailbox|sap-v4/.test(make)) throw new Error('old bridge text left in the Make part');

const head = `// Make → Figma — plugin main thread. Standalone: talks only to the Make → Figma bridge (make-figma/bridge/server.js, port ${PORT}).
// GENERATED by make-figma/build.js from plugin/sap-bridge/code.js — do not edit by hand.
const BASE = 'http://localhost:${PORT}';
let token = null;
let treeBusy = false;
`;
const tail = `
// ─── start ───
figma.showUI(__html__, { width: 340, height: 150, themeColors: true });
(async function init() {
  token = (await figma.clientStorage.getAsync('makeFigmaToken')) || null;
  healthCheck();
  setInterval(healthCheck, 3000);
})();

async function healthCheck() {
  const r = await api('/health');
  if (r.status === 0) { send({ type: 'status', value: 'looking' }); return; }
  const j = r.json;
  if (!j || j.app !== 'make-figma-bridge') { send({ type: 'status', value: 'wrong-bridge' }); return; }
  if (!token) { await doPair(); if (!token) return; }
  send({ type: 'status', value: 'connected', extension: !!j.extension, extVersion: j.extVersion || '' });
}
async function doPair() {
  token = null;
  const r = await api('/pair');
  if (r.status === 200 && r.json && r.json.token) { token = r.json.token; await figma.clientStorage.setAsync('makeFigmaToken', token); }
  else if (r.status === 409) send({ type: 'status', value: 'pair-locked' });
  else send({ type: 'status', value: 'looking' });
}

figma.ui.onmessage = async function (msg) {
  switch (msg.type) {
    case 'make-dump': await makeBuild(msg.json); break;
    case 'make-link': await makeLink(msg.url); break;
    case 'show-node': if (msg.nodeId) await showNode(msg.nodeId); break;
    case 'resize': figma.ui.resize(340, Math.max(90, Math.min(760, Math.round(msg.height)))); break;
    default: break;
  }
};
`;
fs.mkdirSync(OUT, { recursive: true });
const code = head + engine + helpers + logos + make + tail;
new Function(code);                                                       // syntax check only (nothing runs)
fs.writeFileSync(path.join(OUT, 'code.js'), code);
fs.writeFileSync(path.join(OUT, 'manifest.json'), JSON.stringify({
  name: 'Make → Figma', id: 'make-figma-standalone', api: '1.0.0', main: 'code.js', ui: 'ui.html', editorType: ['figma'],
  documentAccess: 'dynamic-page', enablePrivatePluginApi: true,
  networkAccess: { allowedDomains: ['none'], devAllowedDomains: [`http://localhost:${PORT}`] },
}, null, 2));
if (!fs.existsSync(path.join(OUT, 'ui.html'))) throw new Error('make-figma/plugin/ui.html is missing');
execFileSync(process.execPath, [path.join(ROOT, 'build', 'make-extension.js')], { stdio: 'inherit', env: Object.assign({}, process.env, { MAKE_EXT_PORT: String(PORT), MAKE_EXT_OUT: path.join(__dirname, 'extension'), MAKE_EXT_NAME: 'Make → SAP (standalone)' }) });
console.log(`plugin  ${(code.length / 1024).toFixed(0)} KB → ${OUT}`);
